import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
let output = path.join(root, 'index.html');
let check = false;
for (let i = 0; i < args.length; i++) {
  if (args[i] === '--check') check = true;
  else if (args[i] === '--output' && args[i + 1] && !args[i + 1].startsWith('--')) {
    output = path.resolve(args[++i]);
  } else throw new Error('Usage: node build.mjs [--check] [--output path/to/index.html]');
}

const assets = ['styles.css', 'api.js', 'view-model.js', 'saved-store.js', 'app.js'];
const templatePath = path.join(root, 'src', 'index.template.html');
if ([templatePath, ...assets.map(name => path.join(root, name))].includes(output)) {
  throw new Error('Output must not overwrite an editable source file.');
}
const [template, ...sources] = await Promise.all([
  templatePath, ...assets.map(name => path.join(root, name))
].map(filename => readFile(filename, 'utf8')));

// HTML raw-text elements terminate at their closing tag even inside JS/CSS strings.
const escapeClosingTag = (source, tag) => source.replace(
  new RegExp(`</${tag}`, 'gi'), match => '<\\/' + match.slice(2)
);
let html = template;
const replaceOne = (placeholder, replacement) => {
  if (html.split(placeholder).length !== 2) {
    throw new Error(`Expected exactly one asset placeholder: ${placeholder}`);
  }
  html = html.replace(placeholder, () => replacement);
};
replaceOne('<link rel="stylesheet" href="./styles.css">',
  `<style data-source="styles.css">\n${escapeClosingTag(sources[0], 'style')}\n</style>`);
for (let i = 1; i < assets.length; i++) {
  replaceOne(`<script src="./${assets[i]}" defer></script>`,
    `<script data-source="${assets[i]}">\n${escapeClosingTag(sources[i], 'script')}\n</script>`);
}
html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Generated by npm run build. Edit src/index.template.html and the source assets. -->');

if (check) {
  const existing = await readFile(output, 'utf8').catch(error => {
    if (error.code === 'ENOENT') return null;
    throw error;
  });
  if (existing !== html) {
    console.error('Generated HTML is missing or out of date. Run npm run build.');
    process.exitCode = 1;
  } else console.log('Generated HTML is up to date.');
} else {
  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, html);
  console.log(`Built self-contained HTML: ${output}`);
}
